
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.CFuncao;
import Control.CMembro;
import Control.CMilitante;
import Modelo.MFuncao;
import Modelo.MMembro;
import Modelo.MMilitante;
import Modelo.VMembro;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALFREDO CACONDA
 */
public class MEMBRO extends javax.swing.JFrame {

    /**
     * Creates new form Militante
     */
    public MEMBRO() {
        initComponents();
        txtnome.requestFocus();
        pesquisar("");
        funcao();
        Militante();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnome = new rojeru_san.RSMTextFull();
        btnsalvar = new rojeru_san.RSButtonRiple();
        btnapagar = new rojeru_san.RSButtonRiple();
        btneditar = new rojeru_san.RSButtonRiple();
        btnsalvar1 = new rojeru_san.RSButtonRiple();
        txtdata_de_inicio = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        cbfuncao = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnmilitante = new rojeru_san.RSButton();
        jLabel7 = new javax.swing.JLabel();
        btnmilitante1 = new rojeru_san.RSButton();
        jLabel8 = new javax.swing.JLabel();
        btnmilitante2 = new rojeru_san.RSButton();
        jLabel9 = new javax.swing.JLabel();
        btnmilitante3 = new rojeru_san.RSButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cbmilitante = new javax.swing.JComboBox();
        txtpesquisar = new rojeru_san.RSMTextFull();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(244, 255, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setText("CADASTRO DE MEMBROS");

        txtnome.setBackground(new java.awt.Color(10, 26, 62));
        txtnome.setForeground(new java.awt.Color(255, 255, 255));
        txtnome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtnome.setPlaceholder("NOME DO MILITANTE");
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomeKeyPressed(evt);
            }
        });

        btnsalvar.setBackground(new java.awt.Color(0, 166, 81));
        btnsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/salvar.png"))); // NOI18N
        btnsalvar.setText("SALVAR");
        btnsalvar.setColorHover(new java.awt.Color(87, 159, 218));
        btnsalvar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        btnapagar.setBackground(new java.awt.Color(246, 19, 67));
        btnapagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icons8_Close_20px_2.png"))); // NOI18N
        btnapagar.setText("APAGAR");
        btnapagar.setColorHover(new java.awt.Color(246, 0, 33));
        btnapagar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnapagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnapagarActionPerformed(evt);
            }
        });

        btneditar.setBackground(new java.awt.Color(223, 126, 23));
        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/login.png"))); // NOI18N
        btneditar.setText("EDITAR");
        btneditar.setColorHover(new java.awt.Color(223, 215, 54));
        btneditar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btnsalvar1.setBackground(new java.awt.Color(87, 159, 218));
        btnsalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icons8_Done_40px.png"))); // NOI18N
        btnsalvar1.setText("ACTUALIZAR");
        btnsalvar1.setColorHover(new java.awt.Color(0, 166, 81));
        btnsalvar1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnsalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar1ActionPerformed(evt);
            }
        });

        txtdata_de_inicio.setBackground(new java.awt.Color(10, 26, 62));
        txtdata_de_inicio.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtdata_de_inicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdata_de_inicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdata_de_inicio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtdata_de_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdata_de_inicioMouseClicked(evt);
            }
        });
        txtdata_de_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdata_de_inicioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Data de Nascimento");

        cbfuncao.setBackground(new java.awt.Color(10, 26, 62));
        cbfuncao.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbfuncao.setForeground(new java.awt.Color(255, 255, 255));
        cbfuncao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONAR A FUNÇÃO" }));

        jPanel2.setBackground(new java.awt.Color(10, 26, 62));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PÁGINA INICIAL");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        btnmilitante.setBackground(new java.awt.Color(10, 26, 62));
        btnmilitante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icones/IconMilitante.png"))); // NOI18N
        btnmilitante.setText("MILITANTE");
        btnmilitante.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnmilitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmilitanteActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icones/linhaAzul.png"))); // NOI18N

        btnmilitante1.setBackground(new java.awt.Color(10, 26, 62));
        btnmilitante1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icones/iconMembroo.png"))); // NOI18N
        btnmilitante1.setText("MEMBRO");
        btnmilitante1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnmilitante1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmilitante1ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icones/linhaAzul.png"))); // NOI18N

        btnmilitante2.setBackground(new java.awt.Color(10, 26, 62));
        btnmilitante2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icones/iconFunção.png"))); // NOI18N
        btnmilitante2.setText("FUNÇÃO");
        btnmilitante2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnmilitante2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmilitante2ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icones/linhaAzul.png"))); // NOI18N

        btnmilitante3.setBackground(new java.awt.Color(10, 26, 62));
        btnmilitante3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icones/iconQuota.png"))); // NOI18N
        btnmilitante3.setText("QUOTA");
        btnmilitante3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnmilitante3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmilitante3ActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icones/linhaAzul.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icones/HOME.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icones/linhaAzul.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnmilitante1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmilitante2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmilitante3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 20, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(30, 30, 30))))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnmilitante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmilitante, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmilitante1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmilitante2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmilitante3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(10, 26, 62));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 166, 81));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(10, 26, 62));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        cbmilitante.setBackground(new java.awt.Color(10, 26, 62));
        cbmilitante.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbmilitante.setForeground(new java.awt.Color(255, 255, 255));

        txtpesquisar.setBackground(new java.awt.Color(10, 26, 62));
        txtpesquisar.setForeground(new java.awt.Color(255, 255, 255));
        txtpesquisar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtpesquisar.setPlaceholder("PESQUISAR");
        txtpesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpesquisarMouseClicked(evt);
            }
        });
        txtpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesquisarActionPerformed(evt);
            }
        });
        txtpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisarKeyReleased(evt);
            }
        });

        tbtabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "NOME DO MILITANTE", "GENERO", "NASCIMENTO", "ENDEREÇO", "NOME DO PARTIDO", "DATA DE INGRESSO", "TELEFONE", "EMAIL", "Nº BI", "NIVEL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbtabela);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnsalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnapagar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtnome, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(cbmilitante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbfuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtdata_de_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbfuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbmilitante, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtdata_de_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnapagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
        salvar();

    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btnapagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnapagarActionPerformed
        // TODO add your handling code here:
        if (tbtabela.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "SELECIONA O ITEM QUE PRETENDE APAGAR");
        } else {
            apagar();
            pesquisar("");
        }
    }//GEN-LAST:event_btnapagarActionPerformed
    int id, cont = 0;
    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
        if (tbtabela.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "SELECIONA O ITEM QUE PRETENDE EDITAR");
        } else {
            id = (int) tbtabela.getValueAt(tbtabela.getSelectedRow(), 0);
            cbmilitante.setSelectedItem((String) tbtabela.getValueAt(tbtabela.getSelectedRow(), 1));
            cbfuncao.setSelectedItem((String) tbtabela.getValueAt(tbtabela.getSelectedRow(), 2));
            String data_nascimento = ((String) tbtabela.getValueAt(tbtabela.getSelectedRow(), 3));
            txtdata_de_inicio.setText(data_nascimento);
            txtdata_de_inicio.setText(" " + data_nascimento.replace('-', '/'));
            btnsalvar.setVisible(true);
        }
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnsalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar1ActionPerformed
        // TODO add your handling code here:
        actualizar();

    }//GEN-LAST:event_btnsalvar1ActionPerformed

    private void txtdata_de_inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdata_de_inicioMouseClicked

    }//GEN-LAST:event_txtdata_de_inicioMouseClicked

    private void txtdata_de_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdata_de_inicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdata_de_inicioActionPerformed

    private void txtpesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpesquisarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txtpesquisarMouseClicked

    private void txtpesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisarKeyReleased
        // TODO add your handling code here:
        pesquisar(txtpesquisar.getText());
    }//GEN-LAST:event_txtpesquisarKeyReleased

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new PRINCIPAL().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnmilitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmilitanteActionPerformed
        // TODO add your handling code here:
        new Militante().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnmilitanteActionPerformed

    private void btnmilitante1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmilitante1ActionPerformed
        // TODO add your handling code here:
        new MEMBRO().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnmilitante1ActionPerformed

    private void btnmilitante2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmilitante2ActionPerformed
        // TODO add your handling code here:
        new Funcao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnmilitante2ActionPerformed

    private void btnmilitante3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmilitante3ActionPerformed
        // TODO add your handling code here:
        // new Quota().setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btnmilitante3ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        new PRINCIPAL().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void txtpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesquisarActionPerformed

    private void txtnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MEMBRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MEMBRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MEMBRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MEMBRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MEMBRO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btnapagar;
    private rojeru_san.RSButtonRiple btneditar;
    private rojeru_san.RSButton btnmilitante;
    private rojeru_san.RSButton btnmilitante1;
    private rojeru_san.RSButton btnmilitante2;
    private rojeru_san.RSButton btnmilitante3;
    private rojeru_san.RSButtonRiple btnsalvar;
    private rojeru_san.RSButtonRiple btnsalvar1;
    private javax.swing.JComboBox cbfuncao;
    private javax.swing.JComboBox cbmilitante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbtabela;
    private javax.swing.JFormattedTextField txtdata_de_inicio;
    private rojeru_san.RSMTextFull txtnome;
    private rojeru_san.RSMTextFull txtpesquisar;
    // End of variables declaration//GEN-END:variables

    private void salvar() {
        Control.CMembro c = new CMembro();
        MMembro m = new MMembro();
        String data_inicio = txtdata_de_inicio.getText();
        if (txtdata_de_inicio.getText().equals("") & cbfuncao.getSelectedIndex() == 0) {
            m.mensagem("POR FAVOR PREENCHA OS VALORES VAZIOS");
        } else {
            m.setData_de_inicio(data_inicio);
            m.setFuncao((MFuncao) cbfuncao.getSelectedItem());;
            m.setMilitante((MMilitante) cbmilitante.getSelectedItem());;
            c.salvar(m);

        }
        pesquisar("");
        limpar();

    }

    private void actualizar() {
        Control.CMembro c = new CMembro();
        MMembro m = new MMembro();
        if (txtnome.getText().equals("") & cbfuncao.getSelectedIndex() == 0) {
            m.mensagem("POR FAVOR PREENCHA OS VALORES VAZIOS");
        } else {
            String data_inicio = txtdata_de_inicio.getText();
            m.setData_de_inicio(data_inicio);
            m.setId_militante(id);
            m.setFuncao((MFuncao) cbfuncao.getSelectedItem());;
            m.setMilitante((MMilitante) cbmilitante.getSelectedItem());;
            c.actualizar(m);

        }
        pesquisar("");
        limpar();

    }

    private String buscarData(Date data) {
        SimpleDateFormat f = new SimpleDateFormat("yyyy/MM/dd");
        return f.format(data);
    }

    private void limpar() {
        txtnome.setText("");
        cbfuncao.setSelectedIndex(0);
        txtdata_de_inicio.setText("");
        txtnome.requestFocus();
    }

    public int pesquisar(String pesquisar) {
        int valor = 0;
        CMembro f = new CMembro();
        DefaultTableModel dt = (DefaultTableModel) tbtabela.getModel();
        Object[] recebe = {"CODIGO", "NOME", "FUNÇÃO", "DATA DE INGRESSO"};
        dt.setColumnIdentifiers(recebe);
        dt.setNumRows(0);
        for (VMembro m : f.listar1(pesquisar)) {
            Object[] dado = {m.getId_membro(), m.getNome_militante(), m.getNome_funcao(), m.getData()};
            dt.addRow(dado);
            valor++;
        }
        return valor;
    }

    private void apagar() {
        CMembro m = new CMembro();
        MMembro n = new MMembro();
        int valor = (int) tbtabela.getValueAt(tbtabela.getSelectedRow(), 0);
        n.setId_militante(valor);
        m.apagar(n);
    }

    private void funcao() {
        CFuncao c = new CFuncao();
        for (MFuncao m : c.Consultar()) {
            cbfuncao.addItem(m);
        }
    }

    public void Militante() {
        CMilitante f = new CMilitante();
        for (MMilitante m : f.listar1()) {
            cbmilitante.addItem(m);
        }
    }

}
